added user attributes - previously missing
csc207group76/connecthub pull request #16
Opened 2024-11-16 21:09 UTC by izabellemarianne

2024-11-16 22:44 UTC, ethanliu24 commented on src/main/java/db/DBUserDataAccessObject.java
I've implemented this file to incorporate MongoDB (see #17), so you can remove this file from staging to avoid merge conflicts

2024-11-16 22:47 UTC, ethanliu24 commented on src/main/java/entity/CommonUser.java
>          this.accessLevel = 0;
Pass `0` through the constructor and assign it to this.accessLevel (i.e. `this.accessLevel = accessLevel`). We'll create users through factories, so the initializations should go there.

2024-11-16 22:49 UTC, ethanliu24 commented on src/main/java/entity/CommonUserFactory.java
> +        return new CommonUser(name, password, userID, birthDate, fullName, email);
As to the comment before, pass 0 for accessLevel from here

2024-11-16 22:55 UTC, ethanliu24 commented on src/main/java/use_case/signup/SignupInteractor.java
> +            final SignupOutputData signupOutputData = new SignupOutputData(user.getUsername(), false);
For SignupOutputData, it should contain *all* the information signupInputData has (e.g. userID, password, email, etc)

2024-11-16 22:56 UTC, ethanliu24 commented on src/main/java/use_case/signup/SignupInteractor.java
> +            final User user = userFactory.create(signupInputData.getUsername(), signupInputData.getPassword(), signupInputData.getUserID(), signupInputData.getBirthDate(), signupInputData.getFullName
Check the comment at the very top, we'll create an empty list here for moderating and posts attribute

2024-11-16 22:59 UTC, ethanliu24 commented on src/main/java/entity/UserFactory.java
> +    User create(String name, String password, String userID, String birthDate, String fullName, String email);
update the function parameters accordingly

2024-11-16 23:03 UTC, ethanliu24 requested changes
Nice job! Just some minor changes needed, there are two attributes missing:
- [ ] A `moderating` attribute to store a list of strings (representing posts ids) that the user is moderating
- [ ] A `posts` attribute to store a list of strings (representing post ids) of posts that the user created

Use ArrayList for both of these attributes, see my comments on where to pass them in. Also, remember to update the related classes/functions to these changes. Hopefully after you made these changes, we could merge it in and have our user DAO working!

2024-11-18 18:39 UTC, ethanliu24 commented
@izabellemarianne we only need the changes in the `entity` folder. Please remove everything else from this PR (i.e. unstage from git)

2024-11-18 21:17 UTC, izabellemarianne commented
Sorry about that, I have pushed another commit does that work?

2024-11-18 21:23 UTC, ethanliu24 requested changes
Hey @izabellemarianne, could u also remove the files `src/main/java/app/ConnectHub.java`, `src/main/java/controller/ViewModel.java`, `src/main/java/signup/SignupController.java`, `src/main/java/db/DBUserDataAcessObject.java` as well? Right now in the `Files Changed` tab, you can see that these file are still there, but after u unstage or remove them, you should not see them in there any more.

2024-11-19 20:12 UTC, closed without merging